/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Blank: typeof import('./components/blank.vue')['default']
    Cc: typeof import('./components/cc.vue')['default']
    Ccc: typeof import('./components/ccc.vue')['default']
    Comment: typeof import('./components/comment.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Login: typeof import('./components/login.vue')['default']
    Middle: typeof import('./components/middle.vue')['default']
    MyPage: typeof import('./components/myPage.vue')['default']
    Register: typeof import('./components/register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shezhi: typeof import('./components/shezhi.vue')['default']
    Smiddle: typeof import('./components/smiddle.vue')['default']
    Square: typeof import('./components/square.vue')['default']
    Subscribe: typeof import('./components/subscribe.vue')['default']
    Subscribed: typeof import('./components/subscribed.vue')['default']
    Unloginhome: typeof import('./components/unloginhome.vue')['default']
    UpFooter: typeof import('./components/upFooter.vue')['default']
    UserPage: typeof import('./components/userPage.vue')['default']
    Write: typeof import('./components/write.vue')['default']
  }
}
